server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:

        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**

        - id: produit-service
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/produits/**

        - id: commande-service
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path=/commandes/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

  instance:
    prefer-ip-address: true